/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "rgb(var(--color-surface) / <alpha-value>)",
        "on-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--color-on-surface-variant) / <alpha-value>)",
        "surface-container": "rgb(var(--color-surface-container) / <alpha-value>)",
        "surface-container-low": "rgb(var(--color-surface-container-low) / <alpha-value>)",
        "surface-container-high": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--color-surface-container-highest) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--color-surface-container-lowest) / <alpha-value>)",
        "surface-dim": "rgb(var(--color-surface-dim) / <alpha-value>)",
        "surface-bright": "rgb(var(--color-surface-bright) / <alpha-value>)",
        "primary": "rgb(var(--color-primary) / <alpha-value>)",
        "primary-container": "rgb(var(--color-primary-container) / <alpha-value>)",
        "on-primary": "rgb(var(--color-on-primary) / <alpha-value>)",
        "secondary": "rgb(var(--color-secondary) / <alpha-value>)",
        "secondary-container": "rgb(var(--color-secondary-container) / <alpha-value>)",
        "outline": "rgb(var(--color-outline) / <alpha-value>)",
        "outline-variant": "rgb(var(--color-outline-variant) / <alpha-value>)",
        "error": "rgb(var(--color-error) / <alpha-value>)",
        "error-container": "rgb(var(--color-error-container) / <alpha-value>)",
        "primary-fixed": "#62fcc8",
        "primary-fixed-dim": "#3edfad",
        "secondary-fixed": "#e7deff",
        "secondary-fixed-dim": "#ccbdff",
        "tertiary": "#d8d9d9",
        "tertiary-container": "#bcbdbd",
        "on-tertiary": "#2f3131",
        "on-tertiary-container": "#4a4c4d",
        "on-tertiary-fixed": "#1a1c1c",
        "on-tertiary-fixed-variant": "#454747",
        "tertiary-fixed": "#e2e2e2",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-background": "rgb(var(--color-on-surface) / <alpha-value>)",
        "background": "rgb(var(--color-surface) / <alpha-value>)",
        "on-secondary-fixed-variant": "#4d13c8",
        "on-primary-fixed-variant": "#00513c",
        "inverse-primary": "#006c50",
        "inverse-surface": "rgb(var(--color-on-surface) / <alpha-value>)",
        "on-secondary-fixed": "#1f0060",
        "on-primary-fixed": "#002116",
        "surface-variant": "rgb(var(--color-surface-container-high) / <alpha-value>)",
        "on-primary-container": "rgb(var(--color-on-primary) / <alpha-value>)",
        "on-error": "#ffffff",
        "on-error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "rgb(var(--color-surface) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--color-secondary) / <alpha-value>)",
        catppuccin: {
          latte: {
            base: "#eff1f5",
            mantle: "#e6e9ef",
            crust: "#dce0e8",
            text: "#4c4f69",
            subtext0: "#6c6f85",
            subtext1: "#5c5f77",
            mauve: "#8839ef",
            surface0: "#ccd0da",
            surface1: "#bcc0cc",
            surface2: "#acb0be",
            emerald: "#059669",
          },
          mocha: {
            base: "#1e1e2e",
            mantle: "#181825",
            crust: "#11111b",
            text: "#cdd6f4",
            subtext0: "#a6adc8",
            subtext1: "#bac2de",
            mauve: "#cba6f7",
            surface0: "#313244",
            surface1: "#45475a",
            surface2: "#585b70",
            mint: "#2ed5a4",
          },
        },
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "space-xl": "1.5rem",
        "gutter-lg": "1.25rem",
        "margin-desktop": "1.5rem",
        "margin": "1.25rem",
        "space-lg": "1.25rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "gutter-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "financial-mono": ["JetBrains Mono", "monospace"],
        "body-base": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "caption-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-medium": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "title-base": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "financial-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.025em", fontWeight: "600" }],
        "body-medium": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "title-base": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-hero": ["36px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
