/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#62fcc8",
        "secondary": "#ccbdff",
        "outline-variant": "#3c4a43",
        "surface": "#0f1322",
        "on-tertiary-container": "#4a4c4d",
        "on-surface": "#dfe1f7",
        "surface-tint": "#3edfad",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-tertiary-fixed-variant": "#454747",
        "outline": "#85948c",
        "primary-container": "#2ed5a4",
        "error": "#ffb4ab",
        "on-background": "#dfe1f7",
        "surface-container": "#1b1f2f",
        "secondary-fixed-dim": "#ccbdff",
        "surface-container-high": "#262939",
        "on-tertiary": "#2f3131",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#303445",
        "tertiary": "#d8d9d9",
        "background": "#0f1322",
        "on-secondary-fixed-variant": "#4d13c8",
        "on-primary-fixed-variant": "#00513c",
        "inverse-primary": "#006c50",
        "on-surface-variant": "#bbcac1",
        "surface-bright": "#353849",
        "surface-container-lowest": "#0a0d1c",
        "tertiary-fixed": "#e2e2e2",
        "inverse-surface": "#dfe1f7",
        "on-primary": "#003828",
        "on-secondary-fixed": "#1f0060",
        "secondary-container": "#5018cb",
        "on-primary-fixed": "#002116",
        "surface-dim": "#0f1322",
        "surface-variant": "#303445",
        "on-primary-container": "#005740",
        "on-error": "#690005",
        "surface-container-low": "#171b2a",
        "secondary-fixed": "#e7deff",
        "tertiary-container": "#bcbdbd",
        "on-secondary": "#350097",
        "error-container": "#93000a",
        "inverse-on-surface": "#2c3040",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed-dim": "#3edfad",
        "on-secondary-container": "#bfadff",
        "primary": "#57f2bf",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-md": "1rem",
        "space-xl": "1.5rem",
        "gutter-lg": "1.25rem",
        "margin-desktop": "1.5rem",
        "margin": "1.25rem",
        "space-lg": "1.25rem",
        "space-2xl": "2rem",
        "space-sm": "0.5rem",
        "gutter-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-mobile": "1.25rem",
        "gutter": "1rem",
      },
      fontFamily: {
        "financial-mono": ["JetBrains Mono", "monospace"],
        "body-base": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "caption-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-medium": ["Plus Jakarta Sans", "sans-serif"],
        "label-caps": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "title-base": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "financial-mono": ["14px", { lineHeight: "20px", letterSpacing: "0.1em", fontWeight: "700" }],
        "body-base": ["15px", { lineHeight: "22px", letterSpacing: "0", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "caption-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.025em", fontWeight: "600" }],
        "body-medium": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "36px", letterSpacing: "-0.025em", fontWeight: "700" }],
        "title-base": ["16px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-hero": ["36px", { lineHeight: "40px", letterSpacing: "-0.025em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
